[Paths]
; The directory containing the source Excel files
SourceFolder = C:\Users\jvand\source\repos\ExcelConsolidator\SampleFiles\Directory Of Files

; The path to the Excel template
TemplateFile = C:\Users\jvand\source\repos\ExcelConsolidator\SampleFiles\SampleTemplate.xlsx

; Where the final consolidated file will be saved
OutputFile = C:\Users\jvand\source\repos\ExcelConsolidator\SampleFiles\OutputFile.xlsx